In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(4,name= "input_a")
b = tf.constant(5,name= "input_b")
c= tf.add(a,b,"add_c")
d = tf.multiply (a,b,"mul_d")
e = tf.multiply(c,d,"mul_e")

In [3]:
sess = tf.Session()

In [4]:
print(sess.run(e))

180


# Shape 

In [5]:
g = tf.Graph()
with g.as_default():
    x = tf.constant(8,name="x_const")
    y = tf.constant(10,name="y_const")
    my_sum = tf.add(x,y,name="x_y_sum")
    z = tf.Variable([0],name="z_add")
    z = z.assign([1])
    fin_sum = tf.add(z,my_sum,name="z_my_sum_add")
    with tf.Session() as sess:
        print(fin_sum.eval())

[19]


# broadcasting

In [6]:
with tf.Graph().as_default():
    primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
    ones = tf.constant(1, dtype=tf.int32)
    just_beyond_primes = tf.add(primes, ones)
    with tf.Session() as sess:
        print (just_beyond_primes.eval())

[ 3  4  6  8 12 14]


# matrix multiplication

In [7]:
with tf.Graph().as_default():
  # Create a matrix (2-d tensor) with 3 rows and 4 columns.
  x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                  dtype=tf.int32)

  # Create a matrix with 4 rows and 2 columns.
  y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

  # Multiply `x` by `y`. 
  # The resulting matrix will have 3 rows and 2 columns.
  matrix_multiply_result = tf.matmul(x, y)

  with tf.Session() as sess:
    print (matrix_multiply_result.eval())

[[35 58]
 [35 33]
 [ 1 -4]]


# Numpy and tensorflow

In [8]:
import numpy as np

In [9]:
mat = np.arange(16).reshape(8,2)

In [10]:
with tf.Graph().as_default():
    mat1 = tf.constant(mat)
    mat_reshape = tf.reshape(mat1,[4,4])
    with tf.Session() as sess:
        print(mat_reshape.eval())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## reshape can be used to change the dimension of tensor

In [11]:
with tf.Graph().as_default():
    mat1 = tf.constant(mat)
    mat_reshape_3_dim = tf.reshape(mat1,[2,2,4])
    with tf.Session() as sess:
        print(mat_reshape_3_dim.eval())

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
